id: A5B96416F
title: Averting Obstacles through Sitātapatrā
type: translation
pechas:
- I09FF956E
- IDAD3A68A
- I0E9E8EE4
- I0A079C15
- I7A7C0047
- I44E6C54C
- IB6997CE6
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:57:38.403900
  last_modified_at: 2023-01-04 12:57:38.403909
  collections:
  - Lhodrak Namkha Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  I09FF956E/7AB9: C9EF
  IDAD3A68A/F4F1: C9EF
  I0E9E8EE4/0991: C9EF
  I0A079C15/13A1: C9EF
  I7A7C0047/C4B5: C9EF
  I44E6C54C/3792: C9EF
  IB6997CE6/2C5B: C9EF
